In [2]:
import os #provides functions for interacting with the operating system
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, explained_variance_score, mean_absolute_error, mean_squared_error
from math import sqrt
from datetime import datetime

In [3]:
confirmed = pd.read_csv('C:/Users/maja1/OneDrive/Dokumenty/COVID-19-master/COVID-19-master/csse_covid_19_data/csse_covid_19_time_series//time_series_covid19_confirmed_global.csv')
deaths = pd.read_csv('C:/Users/maja1/OneDrive/Dokumenty/COVID-19-master/COVID-19-master/csse_covid_19_data/csse_covid_19_time_series//time_series_covid19_deaths_global.csv')
recovered = pd.read_csv('C:/Users/maja1/OneDrive/Dokumenty/COVID-19-master/COVID-19-master/csse_covid_19_data/csse_covid_19_time_series//time_series_covid19_recovered_global.csv')

print(confirmed.shape)
print(deaths.shape)
print(recovered.shape)

confirmed.head()

(264, 86)
(264, 86)
(250, 86)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20
0,NaN,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,281,299,349,367,423,444,484,521,555,607
1,NaN,Albania,41.1533,20.1683,0,0,0,0,0,0,...,304,333,361,377,383,400,409,416,433,446
2,NaN,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,1171,1251,1320,1423,1468,1572,1666,1761,1825,1914
3,NaN,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,439,466,501,525,545,564,583,601,601,638
4,NaN,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,8,10,14,16,17,19,19,19,19,19

In [4]:

confirmed2_transform = pd.melt(confirmed, id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], var_name=['Date'])
deaths2_transform = pd.melt(deaths, id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], var_name=['Date'])
recovered_transform = pd.melt(recovered, id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], var_name=['Date'])


print( confirmed2_transform.shape)
print(deaths2_transform.shape)
print( recovered_transform.shape)


confirmed2_transform.head()

(21648, 6)
(21648, 6)
(20500, 6)

  Province/State Country/Region      Lat     Long     Date  value
0            NaN    Afghanistan  33.0000  65.0000  1/22/20      0
1            NaN        Albania  41.1533  20.1683  1/22/20      0
2            NaN        Algeria  28.0339   1.6596  1/22/20      0
3            NaN        Andorra  42.5063   1.5218  1/22/20      0
4            NaN         Angola -11.2027  17.8739  1/22/20      0

In [5]:
confirmed2_transform['Date'] = pd.to_datetime(confirmed2_transform['Date'])
deaths2_transform['Date'] = pd.to_datetime(deaths2_transform['Date'])
recovered_transform['Date'] = pd.to_datetime(recovered_transform['Date'])


confirmed2_transform.columns = confirmed2_transform.columns.str.replace('value', 'Confirmed')
deaths2_transform.columns = deaths2_transform.columns.str.replace('value', 'Deaths')
recovered_transform.columns = recovered_transform.columns.str.replace('value', 'Recovered')

In [6]:
confirmed2_transform.isnull().sum()

Province/State    14924
Country/Region        0
Lat                   0
Long                  0
Date                  0
Confirmed             0
dtype: int64

In [7]:
deaths2_transform.isnull().sum()

Province/State    14924
Country/Region        0
Lat                   0
Long                  0
Date                  0
Deaths                0
dtype: int64

In [8]:
recovered_transform.isnull().sum()

Province/State    15006
Country/Region        0
Lat                   0
Long                  0
Date                  0
Recovered             0
dtype: int64

In [9]:
confirmed2_transform['Province/State'].fillna(confirmed2_transform['Country/Region'], inplace=True)
deaths2_transform['Province/State'].fillna(deaths2_transform['Country/Region'], inplace=True)
recovered_transform['Province/State'].fillna(recovered_transform['Country/Region'], inplace=True)

confirmed2_transform.isnull().sum()

Province/State    0
Country/Region    0
Lat               0
Long              0
Date              0
Confirmed         0
dtype: int64

In [10]:
# Confirmed with Deaths
full_join = confirmed2_transform.merge(deaths2_transform[['Province/State','Country/Region','Date','Deaths']], 
                                      how = 'left', 
                                      left_on = ['Province/State','Country/Region','Date'], 
                                      right_on = ['Province/State', 'Country/Region','Date'])

print(full_join.shape)

# full join with Recovered
full_join = full_join.merge(recovered_transform[['Province/State','Country/Region','Date','Recovered']], 
                                      how = 'left', 
                                      left_on = ['Province/State','Country/Region','Date'], 
                                      right_on = ['Province/State', 'Country/Region','Date'])

print(full_join.shape)

full_join.head()

(21648, 7)
(21648, 8)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered
0,Afghanistan,Afghanistan,33.0000,65.0000,2020-01-22,0,0,0.0
1,Albania,Albania,41.1533,20.1683,2020-01-22,0,0,0.0
2,Algeria,Algeria,28.0339,1.6596,2020-01-22,0,0,0.0
3,Andorra,Andorra,42.5063,1.5218,2020-01-22,0,0,0.0
4,Angola,Angola,-11.2027,17.8739,2020-01-22,0,0,0.0

In [11]:
full_join.isnull().sum()

Province/State       0
Country/Region       0
Lat                  0
Long                 0
Date                 0
Confirmed            0
Deaths               0
Recovered         1230
dtype: int64

In [12]:
full_join['Month-Year'] = full_join['Date'].dt.strftime('%b-%Y')

full_join.head(20)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Month-Year
0,Afghanistan,Afghanistan,33.0000,65.0000,2020-01-22,0,0,0.0,Jan-2020
1,Albania,Albania,41.1533,20.1683,2020-01-22,0,0,0.0,Jan-2020
2,Algeria,Algeria,28.0339,1.6596,2020-01-22,0,0,0.0,Jan-2020
3,Andorra,Andorra,42.5063,1.5218,2020-01-22,0,0,0.0,Jan-2020
4,Angola,Angola,-11.2027,17.8739,2020-01-22,0,0,0.0,Jan-2020
5,Antigua and Barbuda,Antigua and Barbuda,17.0608,-61.7964,2020-01-22,0,0,0.0,Jan-2020
6,Argentina,Argentina,-38.4161,-63.6167,2020-01-22,0,0,0.0,Jan-2020
7,Armenia,Armenia,40.0691,45.0382,2020-01-22,0,0,0.0,Jan-2020
8,Australian Capital Territory,Australia,-35.4735,149.0124,2020-01-22,0,0,0.0,Jan-2020
9,New South Wales,Australia,-33.8688,151.2093,2020-01-22,0,0,0.0,Jan-2020
10,Northern Territory,Australia,-12.4634,130.8456,2020-01-22,0,0,0.0,Jan-2020
11,Queensland,Australia,-28.0167,153.4000,2020-01-22,0,0,0.0,Jan-2020
12,South Australia,Australia,-34.9285,138.6007,2020-01-22,0,0,0.0,Jan-2020
13,Tasmania,Australia,-41.4545,145.9707,2020-01-22,0,0,0.0,Jan-2020
14,Victoria,Australia,-37.8136,144.9631,2020-01-22,0,0,0.0,Jan-2020
15,Western Australia,Australia,-31.9505,115.8605,2020-01-22,0,0,0.0,Jan-2020
16,Austria,Austria,47.5162,14.5501,2020-01-22,0,0,0.0,Jan-2020
17,Azerbaijan,Azerbaijan,40.1431,47.5769,2020-01-22,0,0,0.0,Jan-2020
18,Bahamas,Bahamas,25.0343,-77.3963,2020-01-22,0,0,0.0,Jan-2020
19,Bahrain,Bahrain,26.0275,50.5500,2020-01-22,0,0,0.0,Jan-2020

In [15]:
#creating a new df    
test = full_join[full_join['Province/State'] == 'Anhui']

#creating a new df    
full_join2 = test.copy()

#creating a new date columns - 1
full_join2['Date - 1'] = full_join2['Date'] + pd.Timedelta(days=1)
full_join2.rename(columns={'Confirmed': 'Confirmed - 1', 'Deaths': 'Deaths - 1', 'Recovered': 'Recovered - 1',
                          'Date': 'Date Minus 1'}, inplace=True)

#Joing on the 2 DFs
full_join3 = test.merge(full_join2[['Province/State', 'Country/Region','Confirmed - 1', 'Deaths - 1', 
                            'Recovered - 1', 'Date - 1', 'Date Minus 1']], how = 'outer',
                             left_on = ['Province/State','Country/Region','Date'], 
                             right_on = ['Province/State', 'Country/Region','Date - 1'])

# Additional Calculations
full_join3['Confirmed Daily'] = full_join3['Confirmed'] - full_join3['Confirmed - 1']


test.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Month-Year
49,Anhui,China,31.8257,117.2264,2020-01-22,1,0,0.0,Jan-2020
313,Anhui,China,31.8257,117.2264,2020-01-23,9,0,0.0,Jan-2020
577,Anhui,China,31.8257,117.2264,2020-01-24,15,0,0.0,Jan-2020
841,Anhui,China,31.8257,117.2264,2020-01-25,39,0,0.0,Jan-2020
1105,Anhui,China,31.8257,117.2264,2020-01-26,60,0,0.0,Jan-2020

In [16]:
full_join2.head()

,Province/State,Country/Region,Lat,Long,Date Minus 1,Confirmed - 1,Deaths - 1,Recovered - 1,Month-Year,Date - 1
49,Anhui,China,31.8257,117.2264,2020-01-22,1,0,0.0,Jan-2020,2020-01-23
313,Anhui,China,31.8257,117.2264,2020-01-23,9,0,0.0,Jan-2020,2020-01-24
577,Anhui,China,31.8257,117.2264,2020-01-24,15,0,0.0,Jan-2020,2020-01-25
841,Anhui,China,31.8257,117.2264,2020-01-25,39,0,0.0,Jan-2020,2020-01-26
1105,Anhui,China,31.8257,117.2264,2020-01-26,60,0,0.0,Jan-2020,2020-01-27

In [17]:
full_join3.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Month-Year,Confirmed - 1,Deaths - 1,Recovered - 1,Date - 1,Date Minus 1,Confirmed Daily
0,Anhui,China,31.8257,117.2264,2020-01-22,1.0,0.0,0.0,Jan-2020,NaN,NaN,NaN,NaT,NaT,NaN
1,Anhui,China,31.8257,117.2264,2020-01-23,9.0,0.0,0.0,Jan-2020,1.0,0.0,0.0,2020-01-23,2020-01-22,8.0
2,Anhui,China,31.8257,117.2264,2020-01-24,15.0,0.0,0.0,Jan-2020,9.0,0.0,0.0,2020-01-24,2020-01-23,6.0
3,Anhui,China,31.8257,117.2264,2020-01-25,39.0,0.0,0.0,Jan-2020,15.0,0.0,0.0,2020-01-25,2020-01-24,24.0
4,Anhui,China,31.8257,117.2264,2020-01-26,60.0,0.0,0.0,Jan-2020,39.0,0.0,0.0,2020-01-26,2020-01-25,21.0

In [18]:
## Applying it on all dataset

#creating a new df    
full_join2 = full_join.copy()

#creating a new date columns - 1
full_join2['Date - 1'] = full_join2['Date'] + pd.Timedelta(days=1)
full_join2.rename(columns={'Confirmed': 'Confirmed - 1', 'Deaths': 'Deaths - 1', 'Recovered': 'Recovered - 1',
                          'Date': 'Date Minus 1'}, inplace=True)

#Joing on the 2 DFs
full_join3 = full_join.merge(full_join2[['Province/State', 'Country/Region','Confirmed - 1', 'Deaths - 1', 
                            'Recovered - 1', 'Date - 1', 'Date Minus 1']], how = 'left',
                             left_on = ['Province/State','Country/Region','Date'], 
                             right_on = ['Province/State', 'Country/Region','Date - 1'])

#minus_onedf.rename(columns={'Confirmed': 'Confirmed - 1', 'Deaths': 'Deaths - 1', 'Recovered': 'Recovered - 1'}, inplace=True)

full_join3.head()

# Additional Calculations
full_join3['Confirmed Daily'] = full_join3['Confirmed'] - full_join3['Confirmed - 1']
full_join3['Deaths Daily'] = full_join3['Deaths'] - full_join3['Deaths - 1']
full_join3['Recovered Daily'] = full_join3['Recovered'] - full_join3['Recovered - 1']

print(full_join3.shape)

(21648, 17)

In [19]:
full_join3.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Month-Year,Confirmed - 1,Deaths - 1,Recovered - 1,Date - 1,Date Minus 1,Confirmed Daily,Deaths Daily,Recovered Daily
0,Afghanistan,Afghanistan,33.0000,65.0000,2020-01-22,0,0,0.0,Jan-2020,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN
1,Albania,Albania,41.1533,20.1683,2020-01-22,0,0,0.0,Jan-2020,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN
2,Algeria,Algeria,28.0339,1.6596,2020-01-22,0,0,0.0,Jan-2020,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN
3,Andorra,Andorra,42.5063,1.5218,2020-01-22,0,0,0.0,Jan-2020,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN
4,Angola,Angola,-11.2027,17.8739,2020-01-22,0,0,0.0,Jan-2020,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN

In [20]:
# Additing manually the numbers for first day

full_join3['Confirmed Daily'].loc[full_join3['Date'] == '2020-01-22'] = full_join3['Confirmed']
full_join3['Deaths Daily'].loc[full_join3['Date'] == '2020-01-22'] = full_join3['Deaths']
full_join3['Recovered Daily'].loc[full_join3['Date'] == '2020-01-22'] = full_join3['Recovered']

# deleting columns
del full_join3['Confirmed - 1']
del full_join3['Deaths - 1']
del full_join3['Recovered - 1']
del full_join3['Date - 1']
del full_join3['Date Minus 1']

c:\users\maja1\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [21]:
# Creating additional slicer for easy of use

full_join3['Hubei Vs Rest of the World'] = 'Rest of the World'
full_join3['Hubei Vs Rest of the World'].loc[full_join3['Province/State'] == 'Hubei'] = 'Hubei - Virus birth'

#full_join3[full_join3['Province/State'] == 'Hubei']

In [22]:
full_join3.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Month-Year,Confirmed Daily,Deaths Daily,Recovered Daily,Hubei Vs Rest of the World
0,Afghanistan,Afghanistan,33.0000,65.0000,2020-01-22,0,0,0.0,Jan-2020,0.0,0.0,0.0,Rest of the World
1,Albania,Albania,41.1533,20.1683,2020-01-22,0,0,0.0,Jan-2020,0.0,0.0,0.0,Rest of the World
2,Algeria,Algeria,28.0339,1.6596,2020-01-22,0,0,0.0,Jan-2020,0.0,0.0,0.0,Rest of the World
3,Andorra,Andorra,42.5063,1.5218,2020-01-22,0,0,0.0,Jan-2020,0.0,0.0,0.0,Rest of the World
4,Angola,Angola,-11.2027,17.8739,2020-01-22,0,0,0.0,Jan-2020,0.0,0.0,0.0,Rest of the World

In [24]:
# Setting my path
path = "C:/Users/maja1/OneDrive/Dokumenty/COVID-19-master/Coronavirus"

# Changing my CWD
os.chdir(path)

full_join3.to_csv('CoronaVirus_PowerBI', sep='\t')

In [25]:
# puting unique values in list
dates = full_join3['Date'].unique()

#creating a df with unique
dates = pd.DataFrame(dates, columns=['Date'])

# Ordering df
dates = dates.sort_values(by=['Date'])

# Creating an ordered list now
dates = full_join3['Date'].unique()

print(full_join3.shape)

try:
    del concat_data
except:
    print()
    
try:
    del final_concat_data
except:
    print()
    

for i in dates:
    new_data = full_join3[full_join3['Date'] == i]
    new_data['Cumulative Date'] = i
    print(i)
    
    try:     
        concat_data = pd.concat([concat_data, new_data], ignore_index = True)
        concat_data['Cumulative Date 2'] = i
        print(concat_data['Date'].unique())
        
        try:
            final_concat_data = pd.concat([final_concat_data, concat_data], ignore_index = True)
        except:
            final_concat_data = concat_data

    except:
        concat_data = new_data
        
print(final_concat_data.shape)

(21648, 13)


2020-01-22T00:00:00.000000000
2020-01-23T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000']
2020-01-24T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000']

c:\users\maja1\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
c:\users\maja1\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:32: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

c:\users\maja1\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:37: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

2020-01-25T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000']
2020-01-26T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000']
2020-01-27T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000']
2020-01-28T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000']
2020-01-29T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000']
2020-01-30T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000']
2020-01-31T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000']
2020-02-01T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000']
2020-02-02T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000']
2020-02-03T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000']
2020-02-04T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000']
2020-02-05T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000']
2020-02-06T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000']
2020-02-07T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000']
2020-02-08T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000']
2020-02-09T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000']
2020-02-10T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000']
2020-02-11T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000']
2020-02-12T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000']
2020-02-13T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000']
2020-02-14T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000']

2020-02-15T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000']
2020-02-16T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000']
2020-02-17T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000']
2020-02-18T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000']
2020-02-19T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000']
2020-02-20T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000']
2020-02-21T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000']
2020-02-22T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000']
2020-02-23T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000']
2020-02-24T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000']

2020-02-25T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000']
2020-02-26T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000']
2020-02-27T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000']
2020-02-28T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000']
2020-02-29T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000']
2020-03-01T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000']
2020-03-02T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000']
2020-03-03T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000']

2020-03-04T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000']
2020-03-05T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000']
2020-03-06T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000']
2020-03-07T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000']
2020-03-08T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000']
2020-03-09T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000']

2020-03-10T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000']
2020-03-11T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000']
2020-03-12T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000']
2020-03-13T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000']
2020-03-14T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000']
2020-03-15T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000']

2020-03-16T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000']
2020-03-17T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000']
2020-03-18T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000']
2020-03-19T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000']
2020-03-20T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'

 '2020-03-20T00:00:00.000000000']
2020-03-21T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000']
2020-03-22T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000']
2020-03-23T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000']
2020-03-24T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000']
2020-03-25T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000']

2020-03-26T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000']
2020-03-27T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000']
2020-03-28T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000']
2020-03-29T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000']

2020-03-30T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000']
2020-03-31T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000']
2020-04-01T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000']
2020-04-02T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000']

2020-04-03T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000']
2020-04-04T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000' '2020-04-04T00:00:00.000000000']
2020-04-05T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000' '2020-04-04T00:00:00.000000000'
 '2020-04-05T00:00:00.000000000']
2020-04-06T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000' '2020-04-04T00:00:00.000000000'
 '2020-04-05T00:00:00.000000000' '2020-04-06T00:00:00.000000000']

2020-04-07T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000' '2020-04-04T00:00:00.000000000'
 '2020-04-05T00:00:00.000000000' '2020-04-06T00:00:00.000000000'
 '2020-04-07T00:00:00.000000000']
2020-04-08T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000' '2020-04-04T00:00:00.000000000'
 '2020-04-05T00:00:00.000000000' '2020-04-06T00:00:00.000000000'
 '2020-04-07T00:00:00.000000000' '2020-04-08T00:00:00.000000000']
2020-04-09T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000' '2020-04-04T00:00:00.000000000'
 '2020-04-05T00:00:00.000000000' '2020-04-06T00:00:00.000000000'
 '2020-04-07T00:00:00.000000000' '2020-04-08T00:00:00.000000000'
 '2020-04-09T00:00:00.000000000']
2020-04-10T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000' '2020-04-04T00:00:00.000000000'
 '2020-04-05T00:00:00.000000000' '2020-04-06T00:00:00.000000000'
 '2020-04-07T00:00:00.000000000' '2020-04-08T00:00:00.000000000'
 '2020-04-09T00:00:00.000000000' '2020-04-10T00:00:00.000000000']

2020-04-11T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000' '2020-04-04T00:00:00.000000000'
 '2020-04-05T00:00:00.000000000' '2020-04-06T00:00:00.000000000'
 '2020-04-07T00:00:00.000000000' '2020-04-08T00:00:00.000000000'
 '2020-04-09T00:00:00.000000000' '2020-04-10T00:00:00.000000000'
 '2020-04-11T00:00:00.000000000']
2020-04-12T00:00:00.000000000
['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000000000' '2020-02-22T00:00:00.000000000'
 '2020-02-23T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-02-25T00:00:00.000000000' '2020-02-26T00:00:00.000000000'
 '2020-02-27T00:00:00.000000000' '2020-02-28T00:00:00.000000000'
 '2020-02-29T00:00:00.000000000' '2020-03-01T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-03-04T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2020-03-07T00:00:00.000000000'
 '2020-03-08T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-10T00:00:00.000000000' '2020-03-11T00:00:00.000000000'
 '2020-03-12T00:00:00.000000000' '2020-03-13T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-03-15T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-17T00:00:00.000000000'
 '2020-03-18T00:00:00.000000000' '2020-03-19T00:00:00.000000000'
 '2020-03-20T00:00:00.000000000' '2020-03-21T00:00:00.000000000'
 '2020-03-22T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-24T00:00:00.000000000' '2020-03-25T00:00:00.000000000'
 '2020-03-26T00:00:00.000000000' '2020-03-27T00:00:00.000000000'
 '2020-03-28T00:00:00.000000000' '2020-03-29T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-03-31T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-04-02T00:00:00.000000000'
 '2020-04-03T00:00:00.000000000' '2020-04-04T00:00:00.000000000'
 '2020-04-05T00:00:00.000000000' '2020-04-06T00:00:00.000000000'
 '2020-04-07T00:00:00.000000000' '2020-04-08T00:00:00.000000000'
 '2020-04-09T00:00:00.000000000' '2020-04-10T00:00:00.000000000'
 '2020-04-11T00:00:00.000000000' '2020-04-12T00:00:00.000000000']
(898128, 15)

In [26]:
final_concat_data.to_csv('CoronaVirus_PowerBI - Cumulative Test', sep='\t')

In [27]:
final_concat_data.head()

,Confirmed,Confirmed Daily,Country/Region,Cumulative Date,Cumulative Date 2,Date,Deaths,Deaths Daily,Hubei Vs Rest of the World,Lat,Long,Month-Year,Province/State,Recovered,Recovered Daily
0,0,0.0,Afghanistan,2020-01-22,2020-01-23,2020-01-22,0,0.0,Rest of the World,33.0000,65.0000,Jan-2020,Afghanistan,0.0,0.0
1,0,0.0,Albania,2020-01-22,2020-01-23,2020-01-22,0,0.0,Rest of the World,41.1533,20.1683,Jan-2020,Albania,0.0,0.0
2,0,0.0,Algeria,2020-01-22,2020-01-23,2020-01-22,0,0.0,Rest of the World,28.0339,1.6596,Jan-2020,Algeria,0.0,0.0
3,0,0.0,Andorra,2020-01-22,2020-01-23,2020-01-22,0,0.0,Rest of the World,42.5063,1.5218,Jan-2020,Andorra,0.0,0.0
4,0,0.0,Angola,2020-01-22,2020-01-23,2020-01-22,0,0.0,Rest of the World,-11.2027,17.8739,Jan-2020,Angola,0.0,0.0